apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-100rps-610threads
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      volumes:
      - name: jmeter-test-script
        configMap:
          name: jmeter-test
      containers:
      - name: jmeter-container
        image: vaipali/my-first-repo:jmeter-sleep
        imagePullPolicy: Always
        resources:
          # limits:
          #   cpu: "4"
          #   memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - name: jmeter-test-script
          mountPath: /test_script/jmeter_test.jmx
          subPath: jmeter_test.jmx
        
        command: ["sh", "/jmeter_runner/apache-jmeter-5.6.3/bin/jmeter.sh", "-n", "-t", "/test_script/jmeter_test.jmx", "-l", "out.csv", "-e"]
      restartPolicy: OnFailure
