apiVersion: v1
data:
  jmeter_test.jmx: |

    <?xml version="1.0" encoding="UTF-8"?>
    <jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
      <hashTree>
        <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Test Plan">
          <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <boolProp name="TestPlan.functional_mode">false</boolProp>
          <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
        </TestPlan>
        <hashTree>
          <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Users">
            <boolProp name="ThreadGroup.delayedStart">true</boolProp>
            <intProp name="ThreadGroup.num_threads">610</intProp>
            <intProp name="ThreadGroup.ramp_time">0</intProp>
            <longProp name="ThreadGroup.duration">300</longProp>
            <longProp name="ThreadGroup.delay">0</longProp>
            <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
            <boolProp name="ThreadGroup.scheduler">true</boolProp>
            <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
            <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller">
              <intProp name="LoopController.loops">-1</intProp>
              <boolProp name="LoopController.continue_forever">false</boolProp>
            </elementProp>
          </ThreadGroup>
          <hashTree>
            <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request">
              <stringProp name="HTTPSampler.domain">10.8.2.49</stringProp>
              <stringProp name="HTTPSampler.port">8000</stringProp>
              <stringProp name="HTTPSampler.path">/</stringProp>
              <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
              <stringProp name="HTTPSampler.method">POST</stringProp>
              <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>
              <elementProp name="HTTPsampler.Arguments" elementType="Arguments">
                <collectionProp name="Arguments.arguments">
                  <elementProp name="" elementType="HTTPArgument">
                    <boolProp name="HTTPArgument.always_encode">false</boolProp>
                    <stringProp name="Argument.value">{&#xd;
              &quot;_id&quot;: &quot;65485b432c70f3cfa43c08aa&quot;,&#xd;
              &quot;index&quot;: 0,&#xd;
              &quot;guid&quot;: &quot;2110fa89-13d0-491a-854a-a59fce6c0e70&quot;,&#xd;
              &quot;isActive&quot;: false,&#xd;
              &quot;balance&quot;: &quot;$3,571.66&quot;,&#xd;
              &quot;picture&quot;: &quot;http://placehold.it/32x32&quot;,&#xd;
              &quot;age&quot;: 35,&#xd;
              &quot;eyeColor&quot;: &quot;blue&quot;,&#xd;
              &quot;name&quot;: &quot;Wood Chase&quot;,&#xd;
              &quot;gender&quot;: &quot;male&quot;,&#xd;
              &quot;company&quot;: &quot;INVENTURE&quot;,&#xd;
              &quot;email&quot;: &quot;woodchase@inventure.com&quot;,&#xd;
              &quot;phone&quot;: &quot;+1 (854) 550-2920&quot;,&#xd;
              &quot;address&quot;: &quot;355 Times Placez, Hasty, Florida, 4847&quot;,&#xd;
              &quot;about&quot;: &quot;Aliquip elit Lorem et velit sint nisi dolore Lorem occaecat laborum consectetur enim. Et incididunt voluptate qui deserunt dolore magna aliqua tempor nulla. Ea irure aliquip ex non reprehenderit non aliquip laboris ad minim duis anim. Quis amet enim voluptate qui est incididunt ea nostrud. In elit cillum reprehenderit eiusmod. Laboris reprehenderit velit laboris non Lorem excepteur excepteur. Cupidatat est laboris reprehenderit consectetur incididunt laborum.\r\n&quot;,&#xd;
              &quot;registered&quot;: &quot;2020-07-21T12:38:35 -06:-30&quot;,&#xd;
              &quot;latitude&quot;: -15.079694,&#xd;
              &quot;longitude&quot;: 156.292971,&#xd;
              &quot;tags&quot;: [&#xd;
                  &quot;dolore&quot;,&#xd;
                  &quot;labore&quot;,&#xd;
                  &quot;mollit&quot;,&#xd;
                  &quot;incididunt&quot;,&#xd;
                  &quot;sit&quot;,&#xd;
                  &quot;dolore&quot;,&#xd;
                  &quot;aliqua&quot;&#xd;
              ],&#xd;
              &quot;friends&quot;: [&#xd;
                  {&#xd;
                      &quot;id&quot;: 0,&#xd;
                      &quot;name&quot;: &quot;Carly Pate&quot;&#xd;
                  },&#xd;
                  {&#xd;
                      &quot;id&quot;: 1,&#xd;
                      &quot;name&quot;: &quot;Amy Woods&quot;&#xd;
                  },&#xd;
                  {&#xd;
                      &quot;id&quot;: 2,&#xd;
                      &quot;name&quot;: &quot;Allison Castillo&quot;&#xd;
                  }&#xd;
              ],&#xd;
              &quot;greeting&quot;: &quot;Hello, Wood Chase! You have 1 unread messages.&quot;,&#xd;
              &quot;favoriteFruit&quot;: &quot;apple&quot;&#xd;
          }</stringProp>
                    <stringProp name="Argument.metadata">=</stringProp>
                  </elementProp>
                </collectionProp>
              </elementProp>
            </HTTPSamplerProxy>
            <hashTree>
              <ConstantThroughputTimer guiclass="TestBeanGUI" testclass="ConstantThroughputTimer" testname="Constant Throughput Timer">
                <intProp name="calcMode">1</intProp>
                <doubleProp>
                  <name>throughput</name>
                  <value>6000.0</value>
                  <savedValue>0.0</savedValue>
                </doubleProp>
              </ConstantThroughputTimer>
              <hashTree/>
            </hashTree>
          </hashTree>
        </hashTree>
      </hashTree>
    </jmeterTestPlan>

kind: ConfigMap
metadata:
  name: jmeter-test
